# Generated by Django 2.1.5 on 2019-04-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('college', models.CharField(choices=[('逸夫', '逸夫'), ('学勤', '学勤'), ('思廷', '思廷'), ('祥波', '祥波')], max_length=32)),
                ('note', models.TextField(max_length=256)),
                ('contact', models.TextField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
